# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\data\users\tpo\Tools\GITLAB\finder\app\graphique\MainWindow.ui',
# licensing of 'H:\data\users\tpo\Tools\GITLAB\finder\app\graphique\MainWindow.ui' applies.
#
# Created: Thu Aug 19 18:39:21 2021
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 701)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 400))
        self.textEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textEdit.setStyleSheet("")
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 6, 0, 1, 5)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 5, 0, 1, 5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 4, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 2, 1, 1, 3)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 4, 0, 1, 5)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 5)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_datacenter = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_datacenter.setEnabled(False)
        self.checkBox_datacenter.setObjectName("checkBox_datacenter")
        self.horizontalLayout_2.addWidget(self.checkBox_datacenter)
        self.checkBox_cluster = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_cluster.setEnabled(False)
        self.checkBox_cluster.setObjectName("checkBox_cluster")
        self.horizontalLayout_2.addWidget(self.checkBox_cluster)
        self.checkBox_annotation = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_annotation.setEnabled(False)
        self.checkBox_annotation.setObjectName("checkBox_annotation")
        self.horizontalLayout_2.addWidget(self.checkBox_annotation)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1022, 18))
        self.menuBar.setObjectName("menuBar")
        self.menuParameters = QtWidgets.QMenu(self.menuBar)
        self.menuParameters.setObjectName("menuParameters")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setStyleSheet("")
        self.statusBar.setSizeGripEnabled(True)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuParameters.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Finder", None, -1))
        self.lineEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "\"Serveur_1\", \"Serv\", \"124\", \"CDV\" etc.. Possibilité de saisir plusieurs entrées séparées par un espace.", None, -1))
        self.checkBox_datacenter.setText(QtWidgets.QApplication.translate("MainWindow", "Datacenter VMware", None, -1))
        self.checkBox_cluster.setText(QtWidgets.QApplication.translate("MainWindow", "Cluster VMware", None, -1))
        self.checkBox_annotation.setText(QtWidgets.QApplication.translate("MainWindow", "Annotation VMware", None, -1))
        self.menuParameters.setTitle(QtWidgets.QApplication.translate("MainWindow", "Paramètres", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "Fichier", None, -1))
        self.menuAbout.setTitle(QtWidgets.QApplication.translate("MainWindow", "A propos", None, -1))

